"""empty message

Revision ID: c1e96ed0d2e9
Revises: 8bd95b88e109
Create Date: 2016-08-27 11:26:49.536551

"""

# revision identifiers, used by Alembic.
revision = 'c1e96ed0d2e9'
down_revision = '8bd95b88e109'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applicant', sa.Column('college', sa.String(length=16), nullable=True))
    op.add_column('applicant', sa.Column('major', sa.String(length=16), nullable=True))
    op.add_column('applicant', sa.Column('name', sa.String(length=16), nullable=True))
    op.add_column('applicant', sa.Column('phone', sa.String(length=11), nullable=True))
    op.add_column('applicant', sa.Column('qq', sa.String(length=16), nullable=True))
    op.add_column('applicant', sa.Column('sex', sa.CHAR(length=1), nullable=True))
    op.create_unique_constraint(None, 'applicant', ['phone'])
    op.create_unique_constraint(None, 'applicant', ['qq'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'applicant', type_='unique')
    op.drop_constraint(None, 'applicant', type_='unique')
    op.drop_column('applicant', 'sex')
    op.drop_column('applicant', 'qq')
    op.drop_column('applicant', 'phone')
    op.drop_column('applicant', 'name')
    op.drop_column('applicant', 'major')
    op.drop_column('applicant', 'college')
    ### end Alembic commands ###
