"""empty message

Revision ID: fa4e88d8eadd
Revises: 5dd7c079e16f
Create Date: 2016-09-02 21:44:49.517251

"""

# revision identifiers, used by Alembic.
revision = 'fa4e88d8eadd'
down_revision = '5dd7c079e16f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('college', sa.Column('abbr', sa.String(length=16), nullable=True))
    op.create_unique_constraint(None, 'college', ['abbr'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'college', type_='unique')
    op.drop_column('college', 'abbr')
    ### end Alembic commands ###
