"""empty message

Revision ID: 6c1c20c35f4d
Revises: None
Create Date: 2016-08-25 01:28:49.686514

"""

# revision identifiers, used by Alembic.
revision = '6c1c20c35f4d'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applicant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.SmallInteger(), server_default='0', nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('home', sa.String(length=16), nullable=True),
    sa.Column('hobby', sa.String(length=64), nullable=True),
    sa.Column('reason', sa.String(length=64), nullable=True),
    sa.Column('first', sa.String(length=8), nullable=True),
    sa.Column('second', sa.String(length=8), nullable=True),
    sa.ForeignKeyConstraint(['first'], ['department.id'], ),
    sa.ForeignKeyConstraint(['second'], ['department.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('major', 'college_id',
               existing_type=mysql.VARCHAR(length=8),
               nullable=True)
    op.add_column('user', sa.Column('depart', sa.String(length=8), nullable=True))
    op.drop_constraint('user_ibfk_2', 'user', type_='foreignkey')
    op.drop_constraint('user_ibfk_1', 'user', type_='foreignkey')
    op.create_foreign_key(None, 'user', 'department', ['depart'], ['id'])
    op.drop_column('user', 'home')
    op.drop_column('user', 'first')
    op.drop_column('user', 'second')
    op.drop_column('user', 'reason')
    op.drop_column('user', 'status')
    op.drop_column('user', 'hobby')
    op.drop_column('user', 'age')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('age', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('hobby', mysql.VARCHAR(length=64), nullable=True))
    op.add_column('user', sa.Column('status', mysql.SMALLINT(display_width=6), server_default=sa.text("'0'"), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('reason', mysql.VARCHAR(length=64), nullable=True))
    op.add_column('user', sa.Column('second', mysql.VARCHAR(length=8), nullable=True))
    op.add_column('user', sa.Column('first', mysql.VARCHAR(length=8), nullable=True))
    op.add_column('user', sa.Column('home', mysql.VARCHAR(length=16), nullable=True))
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.create_foreign_key('user_ibfk_1', 'user', 'department', ['first'], ['id'])
    op.create_foreign_key('user_ibfk_2', 'user', 'department', ['second'], ['id'])
    op.drop_column('user', 'depart')
    op.alter_column('major', 'college_id',
               existing_type=mysql.VARCHAR(length=8),
               nullable=False)
    op.drop_table('applicant')
    ### end Alembic commands ###
