"""empty message

Revision ID: 8bd95b88e109
Revises: 6c1c20c35f4d
Create Date: 2016-08-27 09:21:26.266733

"""

# revision identifiers, used by Alembic.
revision = '8bd95b88e109'
down_revision = '6c1c20c35f4d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applicant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.SmallInteger(), server_default='0', nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('home', sa.String(length=16), nullable=True),
    sa.Column('hobby', sa.String(length=64), nullable=True),
    sa.Column('reason', sa.String(length=64), nullable=True),
    sa.Column('first', sa.String(length=8), nullable=True),
    sa.Column('second', sa.String(length=8), nullable=True),
    sa.ForeignKeyConstraint(['first'], ['department.id'], ),
    sa.ForeignKeyConstraint(['second'], ['department.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('applicant')
    ### end Alembic commands ###
